### ISSUE TITLE
檔案為中文字，檔案排序非常亂

### ISSUE THREAD

**Issue by ChenPoWei** [cypherpunks-core/ethereumbook_zh#15]
問題：檔案為中文字，檔案排序非常亂
提案：
1. 檔案名稱改為 英文&數字
2. 修正內文所有相關連結

**Comment by milochen0418** [comment]
常在使用時，我也是覺得檔案排序有點亂 ... 想改個檔名，讓它有排序效果，並且好翻閱一些

可能把
第N章 - 章節標題
用 ChN - 章節標題來取代

例如  第 3 章 - Milo 很愛穿藍白拖
那就改成
Ch03 - Milo 很愛穿藍白拖

這樣子的話，就可以排序，
再者是 ，我想說，翻來閱讀比較方便。

看看這樣子覺得如何 ?

**Comment by awesome-doge** [comment]
建議使用作者使用的01, 02, 03, 04之所以會這樣。是因為如果用1, 2, 3, 4, 的話到了10, 11, 12，排序會變成1, 10, 11 ,12 , 2, 3，很詭異。

**Comment by milochen0418** [comment]
那我就用 Ch01 blabla  , Ch02 blabla   Ch03 blabla  這樣子如何 ?
還是要直接以數字作為檔名的開頭
01 blabla ,   02 blabla, 03 blabla ?

**Comment by awesome-doge** [comment]
已經完成數字化
