### ISSUE TITLE
第四章，目前在原文中被拿掉

### ISSUE THREAD

**Issue by milochen0418** [cypherpunks-core/ethereumbook_zh#38]
目前的第四章
https://github.com/cypherpunks-core/ethereumbook_zh/blob/master/%E7%AC%AC%E5%9B%9B%E7%AB%A0.asciidoc

在原文中似乎已經不存在，但第四章的內容其實也不錯。
之後可以再看看怎麼處理 ...

**Comment by awesome-doge** [comment]
這本書應該是參考原作的`tech-review`分支https://github.com/ethereumbook/ethereumbook/tree/tech-review

最後原作者在發布的時候，就改掉了。你看他`tech-review`分支第四章一直沒有打勾勾
![螢幕快照 2019-08-31 下午7 18 34](https://user-images.githubusercontent.com/54278075/64063239-30230080-cc24-11e9-8f6c-e03c472b7b9c.png)

**Comment by milochen0418** [comment]
develop 是它主要的branch, 而它主要 branch 底下，有寫到，實體書本的出刊，以這個branch 為主
https://github.com/ethereumbook/ethereumbook/tree/first_edition_first_print

tech-review 的branch 也有一些不準的方
像是它裡面 DApps 章節沒有打勾。但是在實體的紙本書籍中， DApps 卻是一個獨立的章節。
所以我在想 ... 應該是依這個 branch 翻譯比較好 ... 我都是拿著原版英文書籍，一邊看一邊在翻
https://github.com/ethereumbook/ethereumbook/tree/first_edition_first_print
