### ISSUE TITLE
網站發布流程(CI/CD)

### ISSUE THREAD

**Issue by awesome-doge** [cypherpunks-core/ethereumbook_zh#46]
> * 網站的發布依賴`gitbook`指令，他是來自`npm`。
> * 因為本書自帶latex code 所以要安裝 `mathjax`套件，這會在`book.json`看見

@milochen0418 
# 發布成網頁版流程：
1. 執行`gitbook build`生成網頁的文件都在`_book`
2. commit 丟到 master 一趟

檢查是否有 `gh-pages`分支，有的話砍掉，沒的話做一個，預防衝突。

3. GitHub 規定要把html文件丟到 `gh-pages`分支，所以就`git push origin :gh-pages`製造分枝
    > 不過新版的可在repo>>setting 裡面設定要用哪個branch 呈現網頁
4. 進到`gh-pages`分支 刪除所有 `_book` 之外的檔案。
    ```
    git rm --cached -r .
    git clean -df
    ```
    > 執行該行指令之所以不會刪除`_book`文件，是因為在`.gitignore`已經加入了忽略的文件格式。
5. 把`_book`東西複製出來`cp -r _book/* .`
6. 最後再把修改的東西推一波到`gh-pages`分支

# 問題
*   `gh-pages`分支會一直被砍掉

# 解決方案
* 直接把`master`設定成網頁發布，直接把`_book`裡面的程式碼搬到主目錄，缺點就是代碼超亂

**Comment by milochen0418** [comment]
這個問題我之前有研究一下，大概研究到凌晨三點的 XD
https://github.com/cypherpunks-core/ethereumbook_zh/commit/c04a39dcd9c785bdd461836f64e8a8b85233788b
目前的gh-pages branch 我已經是有成功更新了。
可以在不砍 gh-pages branch 的情況下，能正常maintain 

我發現好像沒辦法"成功地"用 pull-request 的方式，讓我從 milochen0418 的 gh-pages的branch 來對 cypherpunks-core 的 gh-pages 作 pull request. 
所以最後的作法，其實就變成直接至  cypherpunks-core 的 gh-pages 上作更新就好了。

方法如下
$ git clone https://github.com/cypherpunks-core/ethereumbook_zh -b gh-pages
開始對該branch作修改
$ git add .
$ git commit -m "commit message"
$ git push -u origin gh-pages

這樣子作就 OK 了。
等等我來試你說的 latex ...  把它更新上去

**Comment by awesome-doge** [comment]
我後來在想不砍gh-pages branch
1. 就手工複製一份`_book`裡面的內容出來
2. 切到 gh-pages branch，把裡面的東西通通砍掉，再貼上去
感覺有點腦，不過，我遇到問題。原本在master生成的公式可以網頁看，**_但是做完第二步就會依樣顯示不出來，不知道哪裡出問題。_**

**Comment by awesome-doge** [comment]
有空的話 往 github action 發展

**Comment by awesome-doge** [comment]
github action 解決
